# Documentation on starting services:
#   http://doc.gitlab.com/ce/ci/services/postgres.html
#   http://doc.gitlab.com/ce/ci/services/mysql.html
services:
  - postgres:latest
  - mysql:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  MYSQL_DATABASE: test_datahandler
  MYSQL_USER: root
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # Define variables for nosetests pointing to the database servers
  # See http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
  POSTGRES_SERVER: postgres
  MYSQL_SERVER: mysql

validate:
  script:
    - flake8
    - pip install -q -e .
    - python setup.py nosetests
