# Documentation on starting services:
#   http://doc.gitlab.com/ce/ci/services/postgres.html
#   http://doc.gitlab.com/ce/ci/services/mysql.html
services:
  - postgres:latest
  - mysql:latest
  - redis:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  MYSQL_DATABASE: test_datahandler
  MYSQL_USER: root
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # Define variables for nosetests pointing to the database servers
  # See http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
  POSTGRES_SERVER: postgres
  MYSQL_SERVER: mysql
  REDIS_SERVER: redis

# Deploy the dev / master branches on gramener.com
deploy-gramener:
  only: [dev, master]
  script:
    - 'ssh -t ubuntu@gramener.com "
        cd /mnt/gramener/apps/gramex;
        git checkout -- .;
        git pull;
        rm -rf /mnt/gramener/apps/v1/guide /mnt/gramener/apps/v1/gramex-update;
        cp -R /home/ubuntu/.config/gramexdata/apps/guide /mnt/gramener/apps/v1/;
        cp -R /mnt/gramener/apps/gramex/gramex/apps/update /mnt/gramener/apps/v1/gramex-update;
        /mnt/gramener/anaconda/bin/gramex setup /mnt/gramener/apps/v1/guide;
        /mnt/gramener/anaconda/bin/gramex setup ui;
      "'

# Deploy the master branch additionally on uat & demo servers
deploy-uat-demo:
  only: [master]
  script:
    - 'ssh -t ubuntu@uat.gramener.com "
        cd ~/gramex;
        git checkout -- .;
        git pull;
        pip install --verbose -e .;
        pip install gramexenterprise;
        gramex setup --all;
        gramex license accept;
      "'
    - 'ssh -t ubuntu@demo.gramener.com "
        cd /mnt/data/apps/gramex/gramex/;
        git checkout -- .;
        git pull;
        pip install --verbose -e .;
        pip install gramexenterprise;
        gramex setup --all;
        gramex license accept;
      "'
