# Documentation on starting services:
#   http://doc.gitlab.com/ce/ci/services/postgres.html
#   http://doc.gitlab.com/ce/ci/services/mysql.html
services:
  - postgres:latest
  - mysql:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  MYSQL_DATABASE: test_datahandler
  MYSQL_USER: root
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # Define variables for nosetests pointing to the database servers
  # See http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
  POSTGRES_SERVER: postgres
  MYSQL_SERVER: mysql

validate:
  except: [deploy]
  script:
    - flake8
    - eslint gramex/apps
    - htmllint gramex/apps/guide/uicomponents/**/*.html
    - bandit gramex --recursive --format csv || true
    - pip install -q -e .
    - python setup.py nosetests

deploy:
  only: [dev, master, deploy]
  script:
    # Setup script for gramener.com
    - 'ssh -t ubuntu@gramener.com "
        cd /mnt/gramener/apps/gramex;
        git checkout -- .;
        git pull;
        rm -rf /mnt/gramener/apps/v1/guide /mnt/gramener/apps/v1/gramex-update;
        cp -R /mnt/gramener/apps/gramex/gramex/apps/guide /mnt/gramener/apps/v1/;
        cp -R /mnt/gramener/apps/gramex/gramex/apps/update /mnt/gramener/apps/v1/gramex-update;
        /mnt/gramener/anaconda/bin/gramex setup /mnt/gramener/apps/v1/guide;
        /mnt/gramener/anaconda/bin/gramex setup ui;
      "'
