url:
    config-reference:
        pattern: /$YAMLURL/reference
        handler: FileHandler
        kwargs:
            path: $YAMLPATH/reference.md
            transform:
                "*.md":
                    function: guide.markdown_template
                    args: [=content, =handler]
                    encoding: utf-8
                    headers:
                        Content-Type: text/html
