url:
    default:                            # A unique name for this handler
        pattern: /(.*)                  # All URLs beginning with /
        handler: FileHandler                # Handler used
        kwargs:                             # Options to the handler
            path: .                         #   path is current dir
            default_filename: index.html    #   default filename
            index: true                     #   display the index
            ignore: ['*']
            allow: ['*.PNG', '*.png', '*.css', '*.eot', '*.gif', '*.html', '*.jpeg', '*.jpg', '*.js', '*.pdf', '*.svg', '*.ttf', '*.woff*', '*.txt']
